Intento 1 de prediccion
  File "C:\Users\jahaz\anaconda3\envs\AI\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *

  File "C:\Users\jahaz\anaconda3\envs\AI\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()

  File "C:\Users\jahaz\anaconda3\envs\AI\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)

  File "C:\Users\jahaz\anaconda3\envs\AI\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)

  File "C:\Users\jahaz\anaconda3\envs\AI\lib\imp.py", line 343, in load_dynamic
    return _load(spec)

ImportError: DLL load failed: Error en una rutina de inicialización de biblioteca de vínculos dinámicos (DLL).


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\jahaz\Desktop\codigolsd\Codigo final\Prediccion.py", line 5, in <module>
    import tensorflow as tf

  File "C:\Users\jahaz\anaconda3\envs\AI\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import

  File "C:\Users\jahaz\anaconda3\envs\AI\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "C:\Users\jahaz\anaconda3\envs\AI\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "C:\Users\jahaz\anaconda3\envs\AI\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\jahaz\anaconda3\envs\AI\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\jahaz\anaconda3\envs\AI\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\jahaz\anaconda3\envs\AI\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\jahaz\anaconda3\envs\AI\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Error en una rutina de inicialización de biblioteca de vínculos dinámicos (DLL).


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.


QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read

QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read
QSocketNotifier: Multiple socket notifiers for same socket 2220 and type Read